export const topapi = [
  {
    _id: 0,
    name: "Casual Cotton T-Shirt",
    price: 25.99,
    strikePrice: 35.99,
    fabric: {
      cotton: true,
      linen: false,
      polyester: false,
      wool: false,
      silk: false,
      denim: false,
      velvet: false,
      fleece: false,
      nylon: false,
      hemp: false,
    },
    design: {
      solidColor: true,
      striped: false,
      checked: false,
      printed: false,
      graphic: false,
      embroidered: false,
      floralPatterned: false,
    },
    style: {
      tShirt: true,
      basicTShirt: true,
      poloTShirt: false,
      henleyTShirt: false,
      vNeckTShirt: false,
      shirt: false,
      casualShirt: false,
      formalShirt: false,
      denimShirt: false,
      linenShirt: false,
      buttonDownShirt: false,
      sweatshirt: false,
      hoodie: false,
      jacket: false,
      denimJacket: false,
      leatherJacket: false,
      sweater: false,
      longSleeveTop: false,
    },
    occasion: {
      casual: true,
      sportswear: false,
      loungewear: false,
      vacation: false,
    },
    season: {
      summer: true,
      winter: false,
      allSeason: false,
      monsoonFriendly: false,
    },
    fit: {
      regularFit: true,
      slimFit: false,
      relaxedFit: false,
      oversized: false,
    },
    sleeveType: {
      shortSleeve: true,
      longSleeve: false,
      sleeveless: false,
      halfSleeve: false,
      fiveSleeve: false,
    },
    color: "Blue",
    size: {
      s: false,
      m: true,
      l: false,
      xl: false,
      xxl: false,
      xxxl: false,
    },
    quantity: 50,
    description:
      "A soft, comfortable, casual cotton t-shirt perfect for summer.",
    mainImage: {
      public_id: "casual-cotton-tshirt-main",
      secure_url: "https://example.com/casual-cotton-tshirt-main.jpg",
    },
    additionalImage: [
      {
        public_id: "casual-cotton-tshirt-side",
        secure_url: "https://example.com/casual-cotton-tshirt-side.jpg",
      },
      {
        public_id: "casual-cotton-tshirt-back",
        secure_url: "https://example.com/casual-cotton-tshirt-back.jpg",
      },
    ],
    createdAt: new Date("2023-09-01T12:00:00Z"),
    updatedAt: new Date("2023-09-10T12:00:00Z"),
  },
  {
    _id: 1,
    name: "Denim Jacket",
    price: 79.99,
    strikePrice: 99.99,
    fabric: {
      cotton: true,
      linen: false,
      polyester: true,
      wool: false,
      silk: false,
      denim: true,
      velvet: false,
      fleece: false,
      nylon: false,
      hemp: false,
    },
    design: {
      solidColor: false,
      striped: false,
      checked: false,
      printed: false,
      graphic: false,
      embroidered: false,
      floralPatterned: false,
    },
    style: {
      jacket: true,
      denimJacket: true,
      leatherJacket: false,
    },
    occasion: {
      casual: true,
      sportswear: false,
      loungewear: false,
      vacation: true,
    },
    season: {
      summer: false,
      winter: true,
      allSeason: true,
      monsoonFriendly: false,
    },
    fit: {
      regularFit: true,
      slimFit: false,
      relaxedFit: false,
      oversized: false,
    },
    sleeveType: {
      longSleeve: true,
      shortSleeve: false,
      sleeveless: false,
      halfSleeve: false,
      fiveSleeve: false,
    },
    color: "Black",
    size: {
      s: false,
      m: false,
      l: true,
      xl: true,
      xxl: false,
      xxxl: false,
    },
    quantity: 20,
    description: "A stylish black denim jacket, perfect for fall and winter.",
    mainImage: {
      public_id: "black-denim-jacket-main",
      secure_url: "https://example.com/black-denim-jacket-main.jpg",
    },
    additionalImage: [
      {
        public_id: "black-denim-jacket-side",
        secure_url: "https://example.com/black-denim-jacket-side.jpg",
      },
    ],
    createdAt: new Date("2023-08-15T12:00:00Z"),
    updatedAt: new Date("2023-08-20T12:00:00Z"),
  },
  {
    _id: 2,
    name: "V-Neck Sweater",
    price: 49.99,
    strikePrice: 59.99,
    fabric: {
      cotton: true,
      linen: false,
      polyester: false,
      wool: true,
      silk: false,
      denim: false,
      velvet: false,
      fleece: false,
      nylon: false,
      hemp: false,
    },
    design: {
      solidColor: true,
      striped: false,
      checked: false,
      printed: false,
      graphic: false,
      embroidered: false,
      floralPatterned: false,
    },
    style: {
      sweater: true,
      vNeckTShirt: true,
    },
    occasion: {
      casual: true,
      sportswear: false,
      loungewear: false,
      vacation: false,
    },
    season: {
      summer: false,
      winter: true,
      allSeason: false,
      monsoonFriendly: false,
    },
    fit: {
      regularFit: false,
      slimFit: true,
      relaxedFit: false,
      oversized: false,
    },
    sleeveType: {
      longSleeve: true,
      shortSleeve: false,
      sleeveless: false,
      halfSleeve: false,
      fiveSleeve: false,
    },
    color: "Gray",
    size: {
      s: false,
      m: false,
      l: true,
      xl: false,
      xxl: true,
      xxxl: false,
    },
    quantity: 30,
    description: "A cozy gray V-neck wool sweater, perfect for winter.",
    mainImage: {
      public_id: "gray-vneck-sweater-main",
      secure_url: "https://example.com/gray-vneck-sweater-main.jpg",
    },
    additionalImage: [
      {
        public_id: "gray-vneck-sweater-side",
        secure_url: "https://example.com/gray-vneck-sweater-side.jpg",
      },
    ],
    createdAt: new Date("2023-07-01T12:00:00Z"),
    updatedAt: new Date("2023-07-10T12:00:00Z"),
  },
];
